name: CI

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Deploy to gh-pages
      run: |
        cd content
        git init
        git config --global user.email "adam.siekiera@outlook.com" && git config --global user.name "AdamSiekierski"
        git add .
        git remote add origin https://AdamSiekierski:${{ secrets.GITHUB_PASSWORD }}@github.com/AdamSiekierski/blog.git
        git checkout -b gh-pages
        git commit -m"Push the new build"
        git push -u origin gh-pages --force
