name: CI

on:
  push:
    branches:
      - master
  repository_dispatch:
    types: contentful-build

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Build Gatsby Page
        run: |
          npm install
          npm run build
        env:
          CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
      - name: Deploy to gh-pages
        run: |
          cd public
          git init
          git config --global user.email "adam.siekiera@outlook.com" && git config --global user.name "AdamSiekierski"
          git add .
          git remote add origin https://AdamSiekierski:${{ secrets.GITHUB_PASSWORD }}@github.com/AdamSiekierski/blog.git
          git checkout -b gh-pages
          git commit -m"Push the new build"
          git push -u origin gh-pages --force
